import { Subject } from '../types/subject';
import { Student } from '../types/student';

export const mockSubjects: Subject[] = [
  { id: 'sub1', code: 'MAT101', name: 'Cálculo Diferencial', credits: 8, prerequisites: [] },
  { id: 'sub2', code: 'MAT102', name: 'Cálculo Integral', credits: 8, prerequisites: ['sub1'] },
  { id: 'sub3', code: 'MAT103', name: 'Cálculo Vectorial', credits: 8, prerequisites: ['sub2'] },
  { id: 'sub4', code: 'FIS101', name: 'Física Mecánica', credits: 7, prerequisites: ['sub1'] },
  { id: 'sub5', code: 'FIS102', name: 'Física Electromagnetismo', credits: 7, prerequisites: ['sub4', 'sub2'] },
  { id: 'sub6', code: 'PRG101', name: 'Programación Básica', credits: 6, prerequisites: [] },
  { id: 'sub7', code: 'PRG201', name: 'Estructura de Datos', credits: 6, prerequisites: ['sub6'] },
  { id: 'sub8', code: 'PRG301', name: 'Algoritmos Avanzados', credits: 6, prerequisites: ['sub7'] },
  { id: 'sub9', code: 'BD101', name: 'Bases de Datos I', credits: 5, prerequisites: ['sub6'] },
  { id: 'sub10', code: 'BD201', name: 'Bases de Datos II', credits: 5, prerequisites: ['sub9'] },
  { id: 'sub11', code: 'RED101', name: 'Redes de Computadoras', credits: 5, prerequisites: ['sub6'] },
  { id: 'sub12', code: 'SO101', name: 'Sistemas Operativos', credits: 6, prerequisites: ['sub7'] },
  { id: 'sub13', code: 'ING101', name: 'Inglés Técnico I', credits: 4, prerequisites: [] },
  { id: 'sub14', code: 'ING201', name: 'Inglés Técnico II', credits: 4, prerequisites: ['sub13'] },
  { id: 'sub15', code: 'ADM101', name: 'Administración de Proyectos', credits: 4, prerequisites: [] },
];

export const mockStudents: Student[] = [
  {
    id: 'stu1',
    name: 'Carlos',
    firstLastName: 'García',
    secondLastName: 'López',
    semester: 4,
    approvedSubjects: ['sub1', 'sub6', 'sub13'],
    failedSubjects: ['sub2', 'sub4'],
    repeatedSubjects: ['sub2', 'sub4'],
    specialSubjects: ['sub2'],
    proposedSubjects: ['sub2', 'sub4', 'sub7', 'sub9'],
    riskScore: 65,
    status: 'PENDING',
  },
  {
    id: 'stu2',
    name: 'María',
    firstLastName: 'Rodríguez',
    secondLastName: 'Martínez',
    semester: 3,
    approvedSubjects: ['sub1', 'sub2', 'sub6', 'sub13', 'sub15'],
    failedSubjects: [],
    repeatedSubjects: [],
    specialSubjects: [],
    proposedSubjects: ['sub3', 'sub4', 'sub7', 'sub9', 'sub14'],
    riskScore: 20,
    status: 'APPROVED',
  },
  {
    id: 'stu3',
    name: 'Juan',
    firstLastName: 'Hernández',
    secondLastName: 'Pérez',
    semester: 5,
    approvedSubjects: ['sub1', 'sub2', 'sub6', 'sub4'],
    failedSubjects: ['sub3', 'sub5', 'sub7'],
    repeatedSubjects: ['sub3', 'sub5', 'sub7'],
    specialSubjects: ['sub3', 'sub7'],
    proposedSubjects: ['sub3', 'sub5', 'sub7', 'sub8'],
    riskScore: 90,
    status: 'MODIFIED',
  },
  {
    id: 'stu4',
    name: 'Ana',
    firstLastName: 'Flores',
    secondLastName: 'González',
    semester: 2,
    approvedSubjects: ['sub1', 'sub6'],
    failedSubjects: ['sub2'],
    repeatedSubjects: [],
    specialSubjects: [],
    proposedSubjects: [],
    riskScore: 0,
    status: 'NOT_SUBMITTED',
  },
  {
    id: 'stu5',
    name: 'Luis',
    firstLastName: 'Torres',
    secondLastName: 'Ramírez',
    semester: 6,
    approvedSubjects: ['sub1', 'sub2', 'sub3', 'sub6', 'sub7', 'sub9', 'sub13'],
    failedSubjects: ['sub4'],
    repeatedSubjects: ['sub4'],
    specialSubjects: [],
    proposedSubjects: ['sub4', 'sub8', 'sub10', 'sub11', 'sub12'],
    riskScore: 45,
    status: 'PENDING',
  },
];
